const { getValidAccessToken, requireGoogleEnv } = require("../_google");

const RESEND_URL = "https://api.resend.com/emails";

function validDate(value) {
  const date = new Date(value || "");
  return Number.isNaN(date.valueOf()) ? null : date;
}

function escapeHtml(value) {
  return String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

async function sendConfirmationEmail({ to, item }) {
  if (!process.env.RESEND_API_KEY || !to) return null;

  const from = process.env.RESEND_FROM_EMAIL || "GrabGrub <onboarding@resend.dev>";
  const start = validDate(item.startsAt);
  const date = start ? start.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "May 26-28, 2026";
  const time = start ? start.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }) : "TBD";
  const code = `GG-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;

  const html = `
    <div style="font-family:Inter,Arial,sans-serif;background:#fff3f6;padding:32px;color:#22131a">
      <div style="max-width:620px;margin:auto;background:#ffffff;border:2px solid #ff5a7d;padding:0;box-shadow:8px 8px 0 #2ee6a6">
        <div style="padding:22px 28px;border-bottom:2px solid #ff5a7d;background:#ff3d6e;color:#fff">
          <div style="font-size:18px;font-weight:700;letter-spacing:0.02em">GrabGrub</div>
          <div style="font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#ffe66d;margin-top:4px">Booking concierge</div>
        </div>
        <div style="padding:30px 28px">
          <div style="display:inline-block;background:#2ee6a6;color:#06261b;border:2px solid #12b880;padding:7px 10px;font-size:12px;font-weight:800;margin-bottom:18px">Booking request confirmed</div>
          <h1 style="font-family:Georgia,serif;font-weight:400;font-size:32px;margin:0 0 10px">${escapeHtml(item.name)}</h1>
          <p style="line-height:1.7;color:#5b3140;margin:0">GrabGrub prepared this booking request and added it to your calendar.</p>
          <div style="margin:24px 0;border-top:2px solid #ffcc00;border-bottom:2px solid #ffcc00;padding:18px 0">
            <p><strong>Confirmation code</strong><br>${escapeHtml(code)}</p>
            <p><strong>Date</strong><br>${escapeHtml(date)}</p>
            <p><strong>Time</strong><br>${escapeHtml(time)}</p>
            <p><strong>Notes</strong><br>${escapeHtml(item.why || "Personalized Rosewood Compass recommendation.")}</p>
          </div>
          <p style="font-size:12px;line-height:1.7;color:#765062;margin:0">Final partner availability may still require venue confirmation. This message was generated by GrabGrub.</p>
        </div>
      </div>
    </div>
  `;

  const response = await fetch(RESEND_URL, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${process.env.RESEND_API_KEY}`
    },
    body: JSON.stringify({
      from,
      to,
      subject: `GrabGrub booking request confirmed: ${item.name}`,
      html
    })
  });

  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message || "Email request failed");
  return data.id || null;
}

module.exports = async function handler(req, res) {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Use POST" });
    return;
  }

  try {
    requireGoogleEnv();
    const accessToken = await getValidAccessToken(req, res);
    if (!accessToken) {
      res.status(401).json({ error: "Google Calendar is not connected" });
      return;
    }

    const items = Array.isArray(req.body?.items) ? req.body.items : [];
    const email = String(req.body?.email || "").trim();
    const publishable = items.filter((item) => validDate(item.startsAt) && validDate(item.endsAt));
    const created = [];
    const emailed = [];

    for (const item of publishable) {
      const calendarBody = {
        summary: item.name || "Rosewood Compass booking",
        description: [
          item.why ? `Why: ${item.why}` : "",
          item.meta ? `Details: ${item.meta}` : "",
          "Added by Rosewood Compass."
        ].filter(Boolean).join("\n"),
        start: { dateTime: item.startsAt },
        end: { dateTime: item.endsAt }
      };

      const response = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events", {
        method: "POST",
        headers: {
          authorization: `Bearer ${accessToken}`,
          "content-type": "application/json"
        },
        body: JSON.stringify(calendarBody)
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error?.message || "Google Calendar insert failed");
      created.push({ title: data.summary, id: data.id, link: data.htmlLink });

      if (email) {
        const emailId = await sendConfirmationEmail({ to: email, item });
        if (emailId) emailed.push(emailId);
      }
    }

    res.status(200).json({ created, emailed, skipped: items.length - publishable.length });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};
